version: 2

project_name: publer-analytics-report

dist: dist

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: publer-analytics-report
    main: ./main.go
    binary: publer-analytics-report
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - publer-analytics-report
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - config.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: christophberger
    name: publer-analytics-report
  draft: false
  prerelease: auto
  mode: replace
